spring:
  application:
    name: springbucks-batch
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springbucks
    username: testdb
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.github.xuyh.batchservice.core.mapper
  executor-type: batch